* Generated by CDO operator gradsdes
*
DSET  ^DATA_2D_LND_mean.nc
DTYPE  NetCDF
XDEF 144 LINEAR 0.000000 2.500000
YDEF 96 LINEAR -90.000000 1.894737
ZDEF 1 LEVELS 0 
TDEF 1 LINEAR 00:23Z30jun2017 1mn
TITLE  DATA_2D_LND_mean.nc  144x96 grid
UNDEF  1e+36
VARS  3
bcdep              0  t,y,x  total BC deposition (dry+wet) from atmosphere  [kg/m^2/s]
snobcmcl           0  t,y,x  mass of BC in snow column  [kg/m2]
snobcmsl           0  t,y,x  mass of BC in top snow layer  [kg/m2]
ENDVARS
